from locator_tests import *
from association_tests import *
from construct_tests import *
from name_tests import *
from occurrence_tests import *
from reifiable_tests import *
from role_tests import *
from same_topic_map_tests import *
from scoped_tests import *
from topic_map_system_tests import *
from topic_map_tests import *
from topic_tests import *
from typed_tests import *
from variant_tests import *
